args<-commandArgs(T)

#dat=read.table("p.txt",sep="\t",head=F)
dat=read.table(args[1],sep="\t",head=F)
head(dat)
#q=p.adjust(dat[,4],method="BH")
q=p.adjust(dat[,1],method="BH")
head(q)
#dat2=cbind(dat,q)
write.table(q,args[2],quote=F,sep="\t",row.names=F,col.names=F)
#write.table(q,"padj.txt",quote=F,sep="\t",row.names=F,col.names=F)
